[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Handle Next.js SSR and API routes
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# For client-side routing - fallback for non-API/static routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200
  force = false

# Set proper cache headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'none'"

# Cache Next.js static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = '/_next/image/*'
query = { q = ':quality', url = ':url', w = ':width' }
to = '/.netlify/images?url=:url&w=:width&q=:quality'
status = 200
force = true 