export const colorSystem = {
  light: {
    background: {
      primary: 'bg-white-smoke',
      secondary: 'bg-silver-lake-blue/10',
      tertiary: 'bg-silver-lake-blue/20',
      elevated: 'bg-white-smoke shadow-sm',
      card: 'bg-white-smoke border border-silver-lake-blue/30 shadow-sm',
      input: 'bg-white-smoke border border-silver-lake-blue/50',
      badge: 'bg-silver-lake-blue/20',
      highlight: 'bg-silver-lake-blue/10',
      skeleton: 'bg-silver-lake-blue/30',
      hover: 'hover:bg-silver-lake-blue/20',
      activeHover: 'hover:bg-silver-lake-blue/30',
    },
    text: {
      primary: 'text-rich-black',
      secondary: 'text-yinmn-blue',
      tertiary: 'text-glaucous',
      disabled: 'text-silver-lake-blue',
      inverse: 'text-white-smoke',
      link: 'text-yinmn-blue hover:text-rich-black',
      heading: 'text-rich-black',
    },
    border: {
      primary: 'border-silver-lake-blue/30',
      secondary: 'border-silver-lake-blue/50',
      focus: 'focus:border-glaucous',
      input: 'border-silver-lake-blue/50',
    },
    interactive: {
      default: 'bg-silver-lake-blue/20 text-rich-black',
      hover: 'hover:bg-silver-lake-blue/30',
      active: 'active:bg-silver-lake-blue/40',
      selected: 'bg-yinmn-blue text-white-smoke',
      disabled: 'bg-silver-lake-blue/20 text-silver-lake-blue',
      focus: 'focus:ring-2 focus:ring-glaucous focus:ring-opacity-50',
    },
    button: {
      primary: 'bg-yinmn-blue hover:bg-rich-black text-white-smoke',
      secondary: 'bg-silver-lake-blue hover:bg-glaucous text-white-smoke',
      outline:
        'bg-white-smoke border border-silver-lake-blue text-yinmn-blue hover:bg-silver-lake-blue/10',
      ghost: 'text-yinmn-blue hover:bg-silver-lake-blue/20',
      danger: 'bg-rich-black hover:bg-yinmn-blue text-white-smoke',
    },
    icon: {
      primary: 'text-yinmn-blue',
      secondary: 'text-glaucous',
      tertiary: 'text-silver-lake-blue',
      interactive: 'text-glaucous hover:text-rich-black',
    },
    status: {
      error: 'bg-rich-black text-white-smoke',
      success: 'bg-yinmn-blue text-white-smoke',
      warning: 'bg-glaucous text-white-smoke',
      info: 'bg-silver-lake-blue text-white-smoke',
    },
  },
  dark: {
    background: {
      primary: 'bg-rich-black',
      secondary: 'bg-yinmn-blue',
      tertiary: 'bg-glaucous',
      elevated: 'bg-yinmn-blue shadow-md',
      card: 'bg-yinmn-blue border border-glaucous shadow-md',
      input: 'bg-yinmn-blue border border-glaucous',
      badge: 'bg-glaucous',
      highlight: 'bg-yinmn-blue',
      skeleton: 'bg-glaucous',
      hover: 'hover:bg-glaucous',
      activeHover: 'hover:bg-silver-lake-blue',
    },
    text: {
      primary: 'text-white-smoke',
      secondary: 'text-white-smoke',
      tertiary: 'text-glaucous/90',
      disabled: 'text-glaucous/70',
      inverse: 'text-rich-black',
      link: 'text-silver-lake-blue hover:text-white-smoke',
      heading: 'text-white-smoke',
    },
    border: {
      primary: 'border-glaucous',
      secondary: 'border-silver-lake-blue/70',
      focus: 'focus:border-silver-lake-blue',
      input: 'border-glaucous',
    },
    interactive: {
      default: 'bg-glaucous text-white-smoke',
      hover: 'hover:bg-silver-lake-blue',
      active: 'active:bg-silver-lake-blue/80',
      selected: 'bg-white-smoke text-rich-black',
      disabled: 'bg-glaucous text-glaucous/70',
      focus: 'focus:ring-2 focus:ring-silver-lake-blue focus:ring-opacity-50',
    },
    button: {
      primary: 'bg-white-smoke hover:bg-silver-lake-blue text-rich-black',
      secondary: 'bg-glaucous hover:bg-silver-lake-blue text-white-smoke',
      outline: 'bg-yinmn-blue border border-glaucous text-silver-lake-blue hover:bg-glaucous',
      ghost: 'text-silver-lake-blue hover:bg-glaucous',
      danger: 'bg-white-smoke hover:bg-silver-lake-blue text-rich-black',
    },
    icon: {
      primary: 'text-silver-lake-blue',
      secondary: 'text-glaucous',
      tertiary: 'text-glaucous/70',
      interactive: 'text-glaucous hover:text-white-smoke',
    },
    status: {
      error: 'bg-white-smoke text-rich-black',
      success: 'bg-silver-lake-blue text-rich-black',
      warning: 'bg-glaucous text-white-smoke',
      info: 'bg-yinmn-blue text-white-smoke',
    },
  },
};
export default colorSystem;
